fix(app): Update code for libre claim rewards
eoscostarica/claim-bp-rewards pull request #4
Opened 2023-04-27 22:19 UTC by fagomezra

fix(app): Update code for libre claim rewards

2023-04-27 22:25 UTC, leisterfrancisco requested changes
Add the list of supported networks in the README file.

In summary: The script supports a safe mechanism to `claimrewards` for the LIBRE network and also it uses a default function for the rest of the networks

2023-04-27 22:34 UTC, leisterfrancisco requested changes

2023-04-27 22:34 UTC, leisterfrancisco commented on README.md
> +4.  For the CLAIM_NETWORK, the supports networks are: `libre`,`libre-testnet`, `antelope`, `jungle`, `telos`, `telos-testnet`, `proton`, `proton-testnet`, `wax`, `.	wax-testnet`
is it correct?

`. wax-testnet`

2023-04-27 22:34 UTC, fagomezra commented
supported networks already added to the README file

2023-04-27 22:36 UTC, fagomezra commented on README.md
> +4.  For the CLAIM_NETWORK, the supports networks are: `libre`,`libre-testnet`, `antelope`, `jungle`, `telos`, `telos-testnet`, `proton`, `proton-testnet`, `wax`, `.	wax-testnet`
no, i already correct them...

2023-04-27 22:38 UTC, leisterfrancisco approved these changes

2023-04-28 17:24 UTC, xavier506 approved these changes
LGTM

2023-04-28 17:24 UTC, merged